sudo: true
dist: trusty
language: go
if: branch = master
services:
  - docker

arch:
  - amd64

go:
- 1.15.x

env:
  global:
    - DOCKER_USERNAME=osmollo
    - AUTHOR=osmollo
    - REPO_NAME=squid-exporter

before_script:
  - export TAG=$(cat VERSION)
  - echo $TAG

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/$REPO_NAME:latest .
  - docker images
  - docker push $DOCKER_USERNAME/$REPO_NAME:latest
  - docker tag $DOCKER_USERNAME/$REPO_NAME:latest $DOCKER_USERNAME/$REPO_NAME:$TAG
  - docker push $DOCKER_USERNAME/$REPO_NAME:$TAG
  - make build

before_deploy:
  - git tag -f "$TAG" -m "$TRAVIS_COMMIT_MESSAGE"
  - git tag

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bin/squid-exporter
  overwrite: true
  skip_cleanup: true
  on:
    repo: $AUTHOR/$REPO_NAME
    all_branches: true
